# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{sinatra-mongo}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Joshua Nichols"]
  s.date = %q{2009-12-10}
  s.description = %q{= sinatra-mongo

Extends Sinatra with an extension method for dealing with monogodb using the ruby driver.


Install it with gem:

    $ gem install sinatra-mongo

Now we can use it an example application.

    require 'sinatra'
    require 'sinatra/mongo'
    
    # Specify the database to use. Defaults to mongo://localhost:27017/default,
    # so you will almost definitely want to change this.
    #
    # Alternatively, you can specify the MONGO_URL as an environment variable
    set :mongo, 'mongo://localhost:27017/sinatra-mongo-example'
    
    # At this point, you can access the Mongo::Database object using the 'mongo' helper:
    
    puts mongo["testCollection"].insert {"name" => "MongoDB", "type" => "database", "count" => 1, "info" => {"x" => 203, "y" => '102'}}
    
    get '/' do
      mongo["testCollection"].find_one
    end

If you need to use authentication, you can specify this in the mongo uri:

    set :mongo, 'mongo://myuser:mypass@localhost:27017/sinatra-mongo-example'

== Mongo Reference

 * http://www.mongodb.org/display/DOCS/Ruby+Tutorial

== Note on Patches/Pull Requests
 
* Fork the project.
* Make your feature addition or bug fix.
* Add tests for it. This is important so I don't break it in a
  future version unintentionally.
* Commit, do not mess with rakefile, version, or history.
  (if you want to have your own version, that is fine but bump version in a commit by itself I can ignore when I pull)
* Send me a pull request. Bonus points for topic branches.

== Copyright

Copyright (c) 2009 Joshua Nichols. See LICENSE for details.
}
  s.email = %q{josh@technicalpickles.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "lib/sinatra/mongo.rb",
     "sinatra-mongo.gemspec",
     "spec/sinatra-mongo_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/technicalpickles/sinatra-mongo}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{A light extension to sinatra for using mongo}
  s.test_files = [
    "spec/sinatra-mongo_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_runtime_dependency(%q<mongo>, [">= 0"])
      s.add_runtime_dependency(%q<sinatra>, [">= 0.9.4"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<mongo>, [">= 0"])
      s.add_dependency(%q<sinatra>, [">= 0.9.4"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
    s.add_dependency(%q<mongo>, [">= 0"])
    s.add_dependency(%q<sinatra>, [">= 0.9.4"])
  end
end

